version: '2'

services:
  ctfd:
    build: /opt/CTFd
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - VIRTUAL_HOST=ctf.cookiez.digital
      - LETSENCRYPT_HOST=ctf.cookiez.digital
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
      internal:

  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.ctf.cookiez.digital
      - LETSENCRYPT_HOST=whoami.ctf.cookiez.digital

  mr-robot:
    image: nginx:alpine
    volumes:
      - /OverflowCTFWorkshop/Web/mr-robot/server:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=mr-robot.ctf.cookiez.digital
      - LETSENCRYPT_HOST=mr-robot.ctf.cookiez.digital

  inspection:
    image: nginx:alpine
    volumes:
      - /OverflowCTFWorkshop/Web/inspection/server:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=inspection.ctf.cookiez.digital
      - LETSENCRYPT_HOST=inspection.ctf.cookiez.digital

  script-kiddies:
    image: nginx:alpine
    volumes:
      - /OverflowCTFWorkshop/Web/script-kiddies/server:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=script-kiddies.ctf.cookiez.digital
      - LETSENCRYPT_HOST=script-kiddies.ctf.cookiez.digital

  crack-me:
    build: /OverflowCTFWorkshop/Misc/crack_me
    ports:
      - "8080:8080"

  scam-shop:
    build: /OverflowCTFWorkshop/Misc/scam_shop/netcat
    ports:
      - "8081:8081"

networks:
    default:
    internal:
        internal: true
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
